---
- name: Install duply and dependencies
  ansible.builtin.apt:
    pkg:
      - duply
      - duplicity
      - lftp

- name: Create duply profile directory
  ansible.builtin.file: path=/root/.duply/rootfs state=directory mode=0700
- name: Create duply config
  ansible.builtin.template: src=duply_conf.j2 dest=/root/.duply/rootfs/conf
- name: Create duply exclude file
  ansible.builtin.copy: src=duply_exclude dest=/root/.duply/rootfs/exclude
- name: Install duply systemd files
  ansible.builtin.copy: src="duply.{{ item }}" dest=/etc/systemd/system/
  loop:
    - timer
    - service

- name: Enable duply timer
  ansible.builtin.service: name=duply.timer enabled=yes state=started daemon_reload=yes
