- name: Install duply and dependencies
  apt:
    pkg:
      - duply
      - duplicity
      - lftp

- name: Create duply profile directory
  file: path=/root/.duply/rootfs state=directory mode=0700

- name: Create duply config
  template: src=duply_conf.j2 dest=/root/.duply/rootfs/conf

- name: Create duply exclude file
  copy: src=duply_exclude dest=/root/.duply/rootfs/exclude

- name: Install duply systemd files
  copy: src="duply.{{ item }}" dest=/etc/systemd/system/
  loop:
    - timer
    - service

- name: Enable duply timer
  service: name=duply.timer enabled=yes state=started daemon_reload=yes
