---
- hosts: all
  roles:
    - { role: base, tags: ['base'] }
    - { role: firewall, tags: ['firewall'] }
    - { role: unattended-upgrades, tags: ['unattended-upgrades'] }
    - { role: docker, tags: ['docker'] }
    - { role: msmtpd, tags: ['msmtpd'] }
    - { role: studentenportal, tags: ['studentenportal'] }
