---
- hosts: all
  roles: 
    - { role: base, tags: ["base"] }
    - { role: firewall, tags: ["firewall"] }
    - { role: unattended-upgrades, tags: ["unattended-upgrades"] }
    - { role: docker, tags: ["docker"] }
    - { role: backups, tags: ["backups"] }
- hosts: nine
  roles:
    - { role: msmtpd, tags: ["msmtpd"] }
    - { role: studentenportal, tags: ["studentenportal"] }
