---

- name: Create studentenportal user
  user:
    name: studentenportal
    state: present
    groups: docker
    shell: /usr/sbin/nologin


- name: Open firewall ports
  include_role: name=firewall tasks_from=open-port
  vars:
      direction: in
      port: "{{ item }}"
      proto: tcp
  loop:
    - 80   # HTTP
    - 443  # HTTPS

- name: Install docker environment file
  template:
    src: studentenportal.env
    dest: /home/studentenportal/studentenportal.env
    owner: studentenportal
    group: studentenportal
    mode: 0600


- name: Clone studentenportal web repository
  git:
    repo: https://github.com/studentenportal/web/
    dest: /home/studentenportal/web
    # FIXME
    version: deployment
  become: true
  become_user: studentenportal

- name: Create data directories
  file:
    path: "/home/studentenportal/{{ item }}"
    state: directory
    owner: studentenportal
    group: studentenportal
  loop:
    - postgres-data
    - media
