---

- name: Create studentenportal user
  user:
    name: studentenportal
    state: present
    groups: docker
    shell: /usr/sbin/nologin


- name: Open firewall ports
  include_role: name=firewall tasks_from=open-port
  vars:
      direction: in
      port: "{{ item }}"
      proto: tcp
  loop:
    - 80   # HTTP
    - 443  # HTTPS

- name: Install docker environment file
  template:
    src: studentenportal.env
    dest: /home/studentenportal/studentenportal.env
    owner: studentenportal
    group: studentenportal
    mode: 0600

- name: Clone studentenportal web repository
  git:
    repo: https://github.com/studentenportal/web/
    dest: /home/studentenportal/web
  become: true
  become_user: studentenportal

- name: Create data directories
  file:
    path: "/home/studentenportal/{{ item.name }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
  loop:
    - name: postgres-data
      owner: 999 # postgres uid
    - name: media
      owner: studentenportal

# https://github.com/pypa/pip/issues/5366
- name: Install newer pip
  pip:
    name: pip
    state: latest
    extra_args: --user
  become: true
  become_user: studentenportal

- name: Install pip packages needed for ansible and docker
  pip:
    name: docker-compose
    state: latest
    extra_args: --user
  become: true
  become_user: studentenportal

- name: Get user information
  getent:
    database: passwd
    key: studentenportal

- name: Set up studentenportal docker containers
  docker_compose:
    project_src: ~/web/
    files: docker-compose-production.yml
  become: true
  become_user: studentenportal
  register: docker_result
  environment:
    UID: "{{ getent_passwd['studentenportal'][1] }}"
    GID: "{{ getent_passwd['studentenportal'][2] }}"

- name: Set up dehydrated account
  command:
    cmd: docker exec -it {{ docker_result.ansible_facts.nginx | list | first }} dehydrated --register --accept-terms
  become: true
  become_user: studentenportal
  register: res
  changed_when: "'+ Account already registered!' not in res.stdout"

- name: Do initial dehydrated run
  command:
    cmd: docker exec -it {{ docker_result.ansible_facts.nginx | list | first }} dehydrated --cron
  become: true
  become_user: studentenportal
  register: res
  changed_when: "'Skipping renew!' not in res.stdout"

- name: Install dehydrated systemd files
  copy: src="studentenportal-dehydrated.{{ item }}" dest=/etc/systemd/system/
  loop:
    - timer
    - service

- name: Enable dehydrated timer
  service: name=studentenportal-dehydrated.timer enabled=yes daemon_reload=yes
