- name: Update apt cache
  apt: update_cache=yes

- name: Install packages needed for ansible
  apt:
    pkg:
    - python-apt

- name: Upgrade system
  apt: upgrade=yes

- name: Add users
  user:
    name: "{{ item.name }}"
    state: present
    groups: "{{ item.groups }}"
  loop: "{{ users }}"

- name: Add SSH keys
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ lookup('file', './files/id_rsa.' + item.name + '.pub') }}"
  loop: "{{ users }}"
